### ISSUE TITLE
List Index Out of Range

### ISSUE THREAD

**Issue by pngcampbell** [gjr80/weewx-highcharts#3]
@gjr80 thanks for all your work on this! I've been wanting to generate highchart graphs from weewx data for a while now but just didn't have the skills to make it happen.  Yesterday I installed v0.2.0 and got it working on my test weewx box running the simulator.  It works fine and no issues generating the JSON files.  However when I installed it on my Raspbery Pi connected to my AcuRite 02064C it generates this list index out of range error.  The week.json generates fine but I never get the year.json.  Looks like something to do with the windrose calculations.  Any thoughts on how to fix this?

Running WeeWX 3.7.1

`weewx[21257]: reportengine: Caught unrecoverable exception in generator weewx.cheetahgenerator.CheetahGenerator
weewx[21257]:         ****  list index out of range
weewx[21257]:         ****  Traceback (most recent call last):
weewx[21257]:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 239, in run
weewx[21257]:         ****      obj.start()
weewx[21257]:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 273, in start
weewx[21257]:         ****      self.run()
weewx[21257]:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 157, in run
weewx[21257]:         ****      ngen = self.generate(gen_dict[section_name], self.gen_ts)
weewx[21257]:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 231, in generate
weewx[21257]:         ****      ngen += self.generate(section[subsection], gen_ts)
weewx[21257]:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 231, in generate
weewx[21257]:         ****      ngen += self.generate(section[subsection], gen_ts)
weewx[21257]:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 319, in generate
weewx[21257]:         ****      default_binding)
weewx[21257]:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 371, in _getSearchList
weewx[21257]:         ****      searchList += obj.get_extension_list(timespan, db_lookup)
weewx[21257]:         ****    File "/usr/share/weewx/user/highchartsSearchX.py", line 1179, in get_extension_list
weewx[21257]:         ****      sle_dict['wr' + _suffix] = self.calcWindRose(timespan, db_lookup, period)
weewx[21257]:         ****    File "/usr/share/weewx/user/highchartsSearchX.py", line 962, in calcWindRose
weewx[21257]:         ****      if (speed_vec_vt[0][i] is None) or (direction_vec_vt[0][i] is None):
weewx[21257]:         ****  IndexError: list index out of range
weewx[21257]:         ****  Generator terminated`

Thanks again!

**Comment by gjr80** [comment]
Hi,

Thanks for letting me know. I have found that these sorts of errors usually come up due to the vagaries of real life data (as distinct from simulated data), None value and gaps in data are often the culprit. The code needs to be robust enough to handle these and clearly I have missed something. On the plus side after a couple of hours getting back into the code I have finally managed to reproduce the error so hopefully I will get it fixed tonite.

Gary

**Comment by gjr80** [comment]
Ok, I think I have this fixed. I say think as the change I made to the code fixed the error on my test system but I am at a bit of a loss as to why it fixed the error. Also picked up another error that was preventing `weewx.conf` settings from overriding `skin.conf` settings.

Please try [v0.2.1](https://github.com/gjr80/weewx-highcharts/releases/tag/v0.2.1) and let me know how it goes.

**Comment by pngcampbell** [comment]
Thanks Gary! That did it.  Seems to be working great now.  I get both JSON files and no errors in syslog.  Thanks for taking the time to resolve this!

Andy

**Comment by gjr80** [comment]
Good news.
