### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by noxx2015** [gjr80/weewx-highcharts#8]
seems that are some problems on my system

get this here:

Jun 23 09:45:42 localhost weewx[6094]: cheetahgenerator: **** Ignoring template /etc/weewx/skins/Highcharts/json/week.json.tmpl
Jun 23 09:45:42 localhost weewx[6094]: cheetahgenerator: **** Reason: cannot find 'wr86400'
Jun 23 09:45:42 localhost weewx[6094]: ****  Traceback (most recent call last):
Jun 23 09:45:42 localhost weewx[6094]: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 332, in generate
Jun 23 09:45:42 localhost weewx[6094]: ****      fd.write(str(compiled_template))
Jun 23 09:45:42 localhost weewx[6094]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1005, in __str__
Jun 23 09:45:42 localhost weewx[6094]: ****      rc = getattr(self, mainMethName)()
Jun 23 09:45:42 localhost weewx[6094]: ****    File "_etc_weewx_skins_Highcharts_json_week_json_tmpl.py", line 346, in respond
Jun 23 09:45:42 localhost weewx[6094]: ****  NotFound: cannot find 'wr86400'
Jun 23 09:45:44 localhost weewx[6094]: cheetahgenerator: Generate failed with exception '<class 'NameMapper.NotFound'>'
Jun 23 09:45:44 localhost weewx[6094]: cheetahgenerator: **** Ignoring template /etc/weewx/skins/Highcharts/json/year.json.tmpl
Jun 23 09:45:44 localhost weewx[6094]: cheetahgenerator: **** Reason: cannot find 'wrmonth'
Jun 23 09:45:44 localhost weewx[6094]: ****  Traceback (most recent call last):
Jun 23 09:45:44 localhost weewx[6094]: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 332, in generate
Jun 23 09:45:44 localhost weewx[6094]: ****      fd.write(str(compiled_template))
Jun 23 09:45:44 localhost weewx[6094]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1005, in __str__
Jun 23 09:45:44 localhost weewx[6094]: ****      rc = getattr(self, mainMethName)()
Jun 23 09:45:44 localhost weewx[6094]: ****    File "_etc_weewx_skins_Highcharts_json_year_json_tmpl.py", line 338, in respond
Jun 23 09:45:44 localhost weewx[6094]: ****  NotFound: cannot find 'wrmonth'
Jun 23 09:45:44 localhost weewx[6094]: cheetahgenerator: Generated 0 files for report Highcharts in 4.23 seconds
Jun 23 09:46:14 localhost weewx[6094]: ftpgenerator: ftp'd 116 files in 30.07 seconds

**Comment by gjr80** [comment]
Could I ask you to make a new post in the [Google Groups weewx-user group](https://groups.google.com/forum/?pli=1#!forum/weewx-user), I prefer to provide support through the weewx-user group and keep this issues list for bugs/code changes etc.

Could you edit `weewx.conf`, set `debug = 1`, save `weewx.conf` then restart WeeWX. Let WeeWX run for at least 3 times your archive period (eg 15 minutes if your archive period is 5 minutes) and then take a log extract from when you started WeeWX through until the 3 archive periods completed. Could you include that log extract and a copy of the `skin.conf` for your Highcharts skin in the post.
